export {
  ANCHOR_ENDPOINT_SIBLING,
  ANCHOR_OFF,
  ANCHOR_ON,
  CHIP_HOVER_PREVIEW,
  CHIP_LIT,
  CHIP_ON,
  CHIP_PENDING_TRACE,
  CHIP_SOURCE,
  LINE_LIT,
  MEMBER_LIT,
  MEMBER_OWNER_LIT,
  TRACE_DEPTH_FADED,
  TRACE_STRENGTH_VAR,
  addSocketState,
  anchorColorClasses,
  clearTraceLitDom,
  createHostState,
  syncTraceLitDom,
  unwindTraceLitDom,
  type HostState,
  type SocketState,
} from "@/lib/traceLitApplyDom";

export {
  applyActiveTraceLit,
  clearTraceLitTimer,
  syncHoverPreviewEdgeIds,
  type TraceLitApplyArgs,
} from "@/lib/traceLitApplySession";
